/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AiWristbandRouteImport } from './routes/ai-wristband'
import { Route as AppRouteImport } from './routes/app'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FitRouteImport } from './routes/fit'
import { Route as ImessageRouteImport } from './routes/imessage'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TextRouteImport } from './routes/text'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as AffiliatesIndexRouteImport } from './routes/affiliates/index'
import { Route as AffiliatesDashboardRouteImport } from './routes/affiliates/dashboard'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareBestAiAssistantsYouCanTextRouteImport } from './routes/compare/best-ai-assistants-you-can-text'
import { Route as CompareChatgptRouteImport } from './routes/compare/chatgpt'
import { Route as CompareSiriRouteImport } from './routes/compare/siri'
import { Route as EarlyAccessIndexRouteImport } from './routes/early-access/index'
import { Route as EarlyAccessAdminRouteImport } from './routes/early-access/admin'
import { Route as EarlyAccessWelcomeRouteImport } from './routes/early-access/welcome'
import { Route as TextLinkRouteImport } from './routes/text_.link'
import { Route as ApiPublicMembershipRouteImport } from './routes/api/public/membership'
import { Route as ApiPublicReplayRouteImport } from './routes/api/public/replay'
import { Route as ApiPublicTRouteImport } from './routes/api/public/t'
import { Route as ApiPublicAccountAppleRouteImport } from './routes/api/public/account/apple'
import { Route as ApiPublicAccountAppleCallbackRouteImport } from './routes/api/public/account/apple-callback'
import { Route as ApiPublicAccountBillingRouteImport } from './routes/api/public/account/billing'
import { Route as ApiPublicAccountGoogleRouteImport } from './routes/api/public/account/google'
import { Route as ApiPublicAccountGoogleCallbackRouteImport } from './routes/api/public/account/google-callback'
import { Route as ApiPublicAccountSessionRouteImport } from './routes/api/public/account/session'
import { Route as ApiPublicBillingCheckoutRouteImport } from './routes/api/public/billing/checkout'
import { Route as ApiPublicBillingCreateCheckoutSessionRouteImport } from './routes/api/public/billing/create-checkout-session'
import { Route as ApiPublicBillingPortalRouteImport } from './routes/api/public/billing/portal'
import { Route as ApiPublicBillingSessionStatusRouteImport } from './routes/api/public/billing/session-status'
import { Route as ApiPublicBillingStartTrialRouteImport } from './routes/api/public/billing/start-trial'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWristbandRoute = AiWristbandRouteImport.update({
  id: '/ai-wristband',
  path: '/ai-wristband',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FitRoute = FitRouteImport.update({
  id: '/fit',
  path: '/fit',
  getParentRoute: () => rootRouteImport,
} as any)
const ImessageRoute = ImessageRouteImport.update({
  id: '/imessage',
  path: '/imessage',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesIndexRoute = AffiliatesIndexRouteImport.update({
  id: '/affiliates/',
  path: '/affiliates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesDashboardRoute = AffiliatesDashboardRouteImport.update({
  id: '/affiliates/dashboard',
  path: '/affiliates/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBestAiAssistantsYouCanTextRoute =
  CompareBestAiAssistantsYouCanTextRouteImport.update({
    id: '/compare/best-ai-assistants-you-can-text',
    path: '/compare/best-ai-assistants-you-can-text',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareChatgptRoute = CompareChatgptRouteImport.update({
  id: '/compare/chatgpt',
  path: '/compare/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSiriRoute = CompareSiriRouteImport.update({
  id: '/compare/siri',
  path: '/compare/siri',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessIndexRoute = EarlyAccessIndexRouteImport.update({
  id: '/early-access/',
  path: '/early-access/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessAdminRoute = EarlyAccessAdminRouteImport.update({
  id: '/early-access/admin',
  path: '/early-access/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessWelcomeRoute = EarlyAccessWelcomeRouteImport.update({
  id: '/early-access/welcome',
  path: '/early-access/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TextLinkRoute = TextLinkRouteImport.update({
  id: '/text_/link',
  path: '/text/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipRoute = ApiPublicMembershipRouteImport.update({
  id: '/api/public/membership',
  path: '/api/public/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReplayRoute = ApiPublicReplayRouteImport.update({
  id: '/api/public/replay',
  path: '/api/public/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTRoute = ApiPublicTRouteImport.update({
  id: '/api/public/t',
  path: '/api/public/t',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountAppleRoute = ApiPublicAccountAppleRouteImport.update({
  id: '/api/public/account/apple',
  path: '/api/public/account/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountAppleCallbackRoute =
  ApiPublicAccountAppleCallbackRouteImport.update({
    id: '/api/public/account/apple-callback',
    path: '/api/public/account/apple-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAccountBillingRoute = ApiPublicAccountBillingRouteImport.update({
  id: '/api/public/account/billing',
  path: '/api/public/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountGoogleRoute = ApiPublicAccountGoogleRouteImport.update({
  id: '/api/public/account/google',
  path: '/api/public/account/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountGoogleCallbackRoute =
  ApiPublicAccountGoogleCallbackRouteImport.update({
    id: '/api/public/account/google-callback',
    path: '/api/public/account/google-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAccountSessionRoute = ApiPublicAccountSessionRouteImport.update({
  id: '/api/public/account/session',
  path: '/api/public/account/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingCheckoutRoute =
  ApiPublicBillingCheckoutRouteImport.update({
    id: '/api/public/billing/checkout',
    path: '/api/public/billing/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingCreateCheckoutSessionRoute =
  ApiPublicBillingCreateCheckoutSessionRouteImport.update({
    id: '/api/public/billing/create-checkout-session',
    path: '/api/public/billing/create-checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingPortalRoute = ApiPublicBillingPortalRouteImport.update({
  id: '/api/public/billing/portal',
  path: '/api/public/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingSessionStatusRoute =
  ApiPublicBillingSessionStatusRouteImport.update({
    id: '/api/public/billing/session-status',
    path: '/api/public/billing/session-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingStartTrialRoute =
  ApiPublicBillingStartTrialRouteImport.update({
    id: '/api/public/billing/start-trial',
    path: '/api/public/billing/start-trial',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing/webhook',
  path: '/api/public/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ai-wristband': typeof AiWristbandRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/fit': typeof FitRoute
  '/imessage': typeof ImessageRoute
  '/join': typeof JoinRoute
  '/landing': typeof LandingRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/order-complete': typeof OrderCompleteRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/text': typeof TextRoute
  '/websites': typeof WebsitesRoute
  '/affiliates/dashboard': typeof AffiliatesDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/best-ai-assistants-you-can-text': typeof CompareBestAiAssistantsYouCanTextRoute
  '/compare/chatgpt': typeof CompareChatgptRoute
  '/compare/siri': typeof CompareSiriRoute
  '/early-access/admin': typeof EarlyAccessAdminRoute
  '/early-access/welcome': typeof EarlyAccessWelcomeRoute
  '/text/link': typeof TextLinkRoute
  '/affiliates/': typeof AffiliatesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/early-access/': typeof EarlyAccessIndexRoute
  '/api/public/membership': typeof ApiPublicMembershipRoute
  '/api/public/replay': typeof ApiPublicReplayRoute
  '/api/public/t': typeof ApiPublicTRoute
  '/api/public/account/apple': typeof ApiPublicAccountAppleRoute
  '/api/public/account/apple-callback': typeof ApiPublicAccountAppleCallbackRoute
  '/api/public/account/billing': typeof ApiPublicAccountBillingRoute
  '/api/public/account/google': typeof ApiPublicAccountGoogleRoute
  '/api/public/account/google-callback': typeof ApiPublicAccountGoogleCallbackRoute
  '/api/public/account/session': typeof ApiPublicAccountSessionRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/create-checkout-session': typeof ApiPublicBillingCreateCheckoutSessionRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/session-status': typeof ApiPublicBillingSessionStatusRoute
  '/api/public/billing/start-trial': typeof ApiPublicBillingStartTrialRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ai-wristband': typeof AiWristbandRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/fit': typeof FitRoute
  '/imessage': typeof ImessageRoute
  '/join': typeof JoinRoute
  '/landing': typeof LandingRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/order-complete': typeof OrderCompleteRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/text': typeof TextRoute
  '/websites': typeof WebsitesRoute
  '/affiliates/dashboard': typeof AffiliatesDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/best-ai-assistants-you-can-text': typeof CompareBestAiAssistantsYouCanTextRoute
  '/compare/chatgpt': typeof CompareChatgptRoute
  '/compare/siri': typeof CompareSiriRoute
  '/early-access/admin': typeof EarlyAccessAdminRoute
  '/early-access/welcome': typeof EarlyAccessWelcomeRoute
  '/text/link': typeof TextLinkRoute
  '/affiliates': typeof AffiliatesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/early-access': typeof EarlyAccessIndexRoute
  '/api/public/membership': typeof ApiPublicMembershipRoute
  '/api/public/replay': typeof ApiPublicReplayRoute
  '/api/public/t': typeof ApiPublicTRoute
  '/api/public/account/apple': typeof ApiPublicAccountAppleRoute
  '/api/public/account/apple-callback': typeof ApiPublicAccountAppleCallbackRoute
  '/api/public/account/billing': typeof ApiPublicAccountBillingRoute
  '/api/public/account/google': typeof ApiPublicAccountGoogleRoute
  '/api/public/account/google-callback': typeof ApiPublicAccountGoogleCallbackRoute
  '/api/public/account/session': typeof ApiPublicAccountSessionRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/create-checkout-session': typeof ApiPublicBillingCreateCheckoutSessionRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/session-status': typeof ApiPublicBillingSessionStatusRoute
  '/api/public/billing/start-trial': typeof ApiPublicBillingStartTrialRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ai-wristband': typeof AiWristbandRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/fit': typeof FitRoute
  '/imessage': typeof ImessageRoute
  '/join': typeof JoinRoute
  '/landing': typeof LandingRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/order-complete': typeof OrderCompleteRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/text': typeof TextRoute
  '/websites': typeof WebsitesRoute
  '/affiliates/dashboard': typeof AffiliatesDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/best-ai-assistants-you-can-text': typeof CompareBestAiAssistantsYouCanTextRoute
  '/compare/chatgpt': typeof CompareChatgptRoute
  '/compare/siri': typeof CompareSiriRoute
  '/early-access/admin': typeof EarlyAccessAdminRoute
  '/early-access/welcome': typeof EarlyAccessWelcomeRoute
  '/text_/link': typeof TextLinkRoute
  '/affiliates/': typeof AffiliatesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/early-access/': typeof EarlyAccessIndexRoute
  '/api/public/membership': typeof ApiPublicMembershipRoute
  '/api/public/replay': typeof ApiPublicReplayRoute
  '/api/public/t': typeof ApiPublicTRoute
  '/api/public/account/apple': typeof ApiPublicAccountAppleRoute
  '/api/public/account/apple-callback': typeof ApiPublicAccountAppleCallbackRoute
  '/api/public/account/billing': typeof ApiPublicAccountBillingRoute
  '/api/public/account/google': typeof ApiPublicAccountGoogleRoute
  '/api/public/account/google-callback': typeof ApiPublicAccountGoogleCallbackRoute
  '/api/public/account/session': typeof ApiPublicAccountSessionRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/create-checkout-session': typeof ApiPublicBillingCreateCheckoutSessionRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/session-status': typeof ApiPublicBillingSessionStatusRoute
  '/api/public/billing/start-trial': typeof ApiPublicBillingStartTrialRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/ai-wristband'
    | '/app'
    | '/checkout'
    | '/faq'
    | '/fit'
    | '/imessage'
    | '/join'
    | '/landing'
    | '/llms.txt'
    | '/mcp'
    | '/order-complete'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/text'
    | '/websites'
    | '/affiliates/dashboard'
    | '/blog/$slug'
    | '/compare/best-ai-assistants-you-can-text'
    | '/compare/chatgpt'
    | '/compare/siri'
    | '/early-access/admin'
    | '/early-access/welcome'
    | '/text/link'
    | '/affiliates/'
    | '/blog/'
    | '/compare/'
    | '/early-access/'
    | '/api/public/membership'
    | '/api/public/replay'
    | '/api/public/t'
    | '/api/public/account/apple'
    | '/api/public/account/apple-callback'
    | '/api/public/account/billing'
    | '/api/public/account/google'
    | '/api/public/account/google-callback'
    | '/api/public/account/session'
    | '/api/public/billing/checkout'
    | '/api/public/billing/create-checkout-session'
    | '/api/public/billing/portal'
    | '/api/public/billing/session-status'
    | '/api/public/billing/start-trial'
    | '/api/public/billing/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/ai-wristband'
    | '/app'
    | '/checkout'
    | '/faq'
    | '/fit'
    | '/imessage'
    | '/join'
    | '/landing'
    | '/llms.txt'
    | '/mcp'
    | '/order-complete'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/text'
    | '/websites'
    | '/affiliates/dashboard'
    | '/blog/$slug'
    | '/compare/best-ai-assistants-you-can-text'
    | '/compare/chatgpt'
    | '/compare/siri'
    | '/early-access/admin'
    | '/early-access/welcome'
    | '/text/link'
    | '/affiliates'
    | '/blog'
    | '/compare'
    | '/early-access'
    | '/api/public/membership'
    | '/api/public/replay'
    | '/api/public/t'
    | '/api/public/account/apple'
    | '/api/public/account/apple-callback'
    | '/api/public/account/billing'
    | '/api/public/account/google'
    | '/api/public/account/google-callback'
    | '/api/public/account/session'
    | '/api/public/billing/checkout'
    | '/api/public/billing/create-checkout-session'
    | '/api/public/billing/portal'
    | '/api/public/billing/session-status'
    | '/api/public/billing/start-trial'
    | '/api/public/billing/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/ai-wristband'
    | '/app'
    | '/checkout'
    | '/faq'
    | '/fit'
    | '/imessage'
    | '/join'
    | '/landing'
    | '/llms.txt'
    | '/mcp'
    | '/order-complete'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/text'
    | '/websites'
    | '/affiliates/dashboard'
    | '/blog/$slug'
    | '/compare/best-ai-assistants-you-can-text'
    | '/compare/chatgpt'
    | '/compare/siri'
    | '/early-access/admin'
    | '/early-access/welcome'
    | '/text_/link'
    | '/affiliates/'
    | '/blog/'
    | '/compare/'
    | '/early-access/'
    | '/api/public/membership'
    | '/api/public/replay'
    | '/api/public/t'
    | '/api/public/account/apple'
    | '/api/public/account/apple-callback'
    | '/api/public/account/billing'
    | '/api/public/account/google'
    | '/api/public/account/google-callback'
    | '/api/public/account/session'
    | '/api/public/billing/checkout'
    | '/api/public/billing/create-checkout-session'
    | '/api/public/billing/portal'
    | '/api/public/billing/session-status'
    | '/api/public/billing/start-trial'
    | '/api/public/billing/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AiWristbandRoute: typeof AiWristbandRoute
  AppRoute: typeof AppRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqRoute: typeof FaqRoute
  FitRoute: typeof FitRoute
  ImessageRoute: typeof ImessageRoute
  JoinRoute: typeof JoinRoute
  LandingRoute: typeof LandingRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TextRoute: typeof TextRoute
  WebsitesRoute: typeof WebsitesRoute
  AffiliatesDashboardRoute: typeof AffiliatesDashboardRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareBestAiAssistantsYouCanTextRoute: typeof CompareBestAiAssistantsYouCanTextRoute
  CompareChatgptRoute: typeof CompareChatgptRoute
  CompareSiriRoute: typeof CompareSiriRoute
  EarlyAccessAdminRoute: typeof EarlyAccessAdminRoute
  EarlyAccessWelcomeRoute: typeof EarlyAccessWelcomeRoute
  TextLinkRoute: typeof TextLinkRoute
  AffiliatesIndexRoute: typeof AffiliatesIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  EarlyAccessIndexRoute: typeof EarlyAccessIndexRoute
  ApiPublicMembershipRoute: typeof ApiPublicMembershipRoute
  ApiPublicReplayRoute: typeof ApiPublicReplayRoute
  ApiPublicTRoute: typeof ApiPublicTRoute
  ApiPublicAccountAppleRoute: typeof ApiPublicAccountAppleRoute
  ApiPublicAccountAppleCallbackRoute: typeof ApiPublicAccountAppleCallbackRoute
  ApiPublicAccountBillingRoute: typeof ApiPublicAccountBillingRoute
  ApiPublicAccountGoogleRoute: typeof ApiPublicAccountGoogleRoute
  ApiPublicAccountGoogleCallbackRoute: typeof ApiPublicAccountGoogleCallbackRoute
  ApiPublicAccountSessionRoute: typeof ApiPublicAccountSessionRoute
  ApiPublicBillingCheckoutRoute: typeof ApiPublicBillingCheckoutRoute
  ApiPublicBillingCreateCheckoutSessionRoute: typeof ApiPublicBillingCreateCheckoutSessionRoute
  ApiPublicBillingPortalRoute: typeof ApiPublicBillingPortalRoute
  ApiPublicBillingSessionStatusRoute: typeof ApiPublicBillingSessionStatusRoute
  ApiPublicBillingStartTrialRoute: typeof ApiPublicBillingStartTrialRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-wristband': {
      id: '/ai-wristband'
      path: '/ai-wristband'
      fullPath: '/ai-wristband'
      preLoaderRoute: typeof AiWristbandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fit': {
      id: '/fit'
      path: '/fit'
      fullPath: '/fit'
      preLoaderRoute: typeof FitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imessage': {
      id: '/imessage'
      path: '/imessage'
      fullPath: '/imessage'
      preLoaderRoute: typeof ImessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates/': {
      id: '/affiliates/'
      path: '/affiliates'
      fullPath: '/affiliates/'
      preLoaderRoute: typeof AffiliatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates/dashboard': {
      id: '/affiliates/dashboard'
      path: '/affiliates/dashboard'
      fullPath: '/affiliates/dashboard'
      preLoaderRoute: typeof AffiliatesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/best-ai-assistants-you-can-text': {
      id: '/compare/best-ai-assistants-you-can-text'
      path: '/compare/best-ai-assistants-you-can-text'
      fullPath: '/compare/best-ai-assistants-you-can-text'
      preLoaderRoute: typeof CompareBestAiAssistantsYouCanTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/chatgpt': {
      id: '/compare/chatgpt'
      path: '/compare/chatgpt'
      fullPath: '/compare/chatgpt'
      preLoaderRoute: typeof CompareChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/siri': {
      id: '/compare/siri'
      path: '/compare/siri'
      fullPath: '/compare/siri'
      preLoaderRoute: typeof CompareSiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access/': {
      id: '/early-access/'
      path: '/early-access'
      fullPath: '/early-access/'
      preLoaderRoute: typeof EarlyAccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access/admin': {
      id: '/early-access/admin'
      path: '/early-access/admin'
      fullPath: '/early-access/admin'
      preLoaderRoute: typeof EarlyAccessAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access/welcome': {
      id: '/early-access/welcome'
      path: '/early-access/welcome'
      fullPath: '/early-access/welcome'
      preLoaderRoute: typeof EarlyAccessWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text_/link': {
      id: '/text_/link'
      path: '/text/link'
      fullPath: '/text/link'
      preLoaderRoute: typeof TextLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership': {
      id: '/api/public/membership'
      path: '/api/public/membership'
      fullPath: '/api/public/membership'
      preLoaderRoute: typeof ApiPublicMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/replay': {
      id: '/api/public/replay'
      path: '/api/public/replay'
      fullPath: '/api/public/replay'
      preLoaderRoute: typeof ApiPublicReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t': {
      id: '/api/public/t'
      path: '/api/public/t'
      fullPath: '/api/public/t'
      preLoaderRoute: typeof ApiPublicTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/apple': {
      id: '/api/public/account/apple'
      path: '/api/public/account/apple'
      fullPath: '/api/public/account/apple'
      preLoaderRoute: typeof ApiPublicAccountAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/apple-callback': {
      id: '/api/public/account/apple-callback'
      path: '/api/public/account/apple-callback'
      fullPath: '/api/public/account/apple-callback'
      preLoaderRoute: typeof ApiPublicAccountAppleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/billing': {
      id: '/api/public/account/billing'
      path: '/api/public/account/billing'
      fullPath: '/api/public/account/billing'
      preLoaderRoute: typeof ApiPublicAccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/google': {
      id: '/api/public/account/google'
      path: '/api/public/account/google'
      fullPath: '/api/public/account/google'
      preLoaderRoute: typeof ApiPublicAccountGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/google-callback': {
      id: '/api/public/account/google-callback'
      path: '/api/public/account/google-callback'
      fullPath: '/api/public/account/google-callback'
      preLoaderRoute: typeof ApiPublicAccountGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/session': {
      id: '/api/public/account/session'
      path: '/api/public/account/session'
      fullPath: '/api/public/account/session'
      preLoaderRoute: typeof ApiPublicAccountSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/checkout': {
      id: '/api/public/billing/checkout'
      path: '/api/public/billing/checkout'
      fullPath: '/api/public/billing/checkout'
      preLoaderRoute: typeof ApiPublicBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/create-checkout-session': {
      id: '/api/public/billing/create-checkout-session'
      path: '/api/public/billing/create-checkout-session'
      fullPath: '/api/public/billing/create-checkout-session'
      preLoaderRoute: typeof ApiPublicBillingCreateCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/portal': {
      id: '/api/public/billing/portal'
      path: '/api/public/billing/portal'
      fullPath: '/api/public/billing/portal'
      preLoaderRoute: typeof ApiPublicBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/session-status': {
      id: '/api/public/billing/session-status'
      path: '/api/public/billing/session-status'
      fullPath: '/api/public/billing/session-status'
      preLoaderRoute: typeof ApiPublicBillingSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/start-trial': {
      id: '/api/public/billing/start-trial'
      path: '/api/public/billing/start-trial'
      fullPath: '/api/public/billing/start-trial'
      preLoaderRoute: typeof ApiPublicBillingStartTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/webhook': {
      id: '/api/public/billing/webhook'
      path: '/api/public/billing/webhook'
      fullPath: '/api/public/billing/webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AiWristbandRoute: AiWristbandRoute,
  AppRoute: AppRoute,
  CheckoutRoute: CheckoutRoute,
  FaqRoute: FaqRoute,
  FitRoute: FitRoute,
  ImessageRoute: ImessageRoute,
  JoinRoute: JoinRoute,
  LandingRoute: LandingRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TextRoute: TextRoute,
  WebsitesRoute: WebsitesRoute,
  AffiliatesDashboardRoute: AffiliatesDashboardRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareBestAiAssistantsYouCanTextRoute:
    CompareBestAiAssistantsYouCanTextRoute,
  CompareChatgptRoute: CompareChatgptRoute,
  CompareSiriRoute: CompareSiriRoute,
  EarlyAccessAdminRoute: EarlyAccessAdminRoute,
  EarlyAccessWelcomeRoute: EarlyAccessWelcomeRoute,
  TextLinkRoute: TextLinkRoute,
  AffiliatesIndexRoute: AffiliatesIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  EarlyAccessIndexRoute: EarlyAccessIndexRoute,
  ApiPublicMembershipRoute: ApiPublicMembershipRoute,
  ApiPublicReplayRoute: ApiPublicReplayRoute,
  ApiPublicTRoute: ApiPublicTRoute,
  ApiPublicAccountAppleRoute: ApiPublicAccountAppleRoute,
  ApiPublicAccountAppleCallbackRoute: ApiPublicAccountAppleCallbackRoute,
  ApiPublicAccountBillingRoute: ApiPublicAccountBillingRoute,
  ApiPublicAccountGoogleRoute: ApiPublicAccountGoogleRoute,
  ApiPublicAccountGoogleCallbackRoute: ApiPublicAccountGoogleCallbackRoute,
  ApiPublicAccountSessionRoute: ApiPublicAccountSessionRoute,
  ApiPublicBillingCheckoutRoute: ApiPublicBillingCheckoutRoute,
  ApiPublicBillingCreateCheckoutSessionRoute:
    ApiPublicBillingCreateCheckoutSessionRoute,
  ApiPublicBillingPortalRoute: ApiPublicBillingPortalRoute,
  ApiPublicBillingSessionStatusRoute: ApiPublicBillingSessionStatusRoute,
  ApiPublicBillingStartTrialRoute: ApiPublicBillingStartTrialRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
