/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Xmxhi72185Char3723ndgdjngfg17w7DothtmlRouteImport } from './routes/xmxhi72185%23ndgdjngfg17w7[.]html'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as EarlyAccessIndexRouteImport } from './routes/early-access/index'
import { Route as EarlyAccessAdminRouteImport } from './routes/early-access/admin'
import { Route as EarlyAccessWelcomeRouteImport } from './routes/early-access/welcome'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as PartnersDashboardRouteImport } from './routes/partners/dashboard'
import { Route as ApiPublicMembershipRouteImport } from './routes/api/public/membership'
import { Route as ApiPublicBillingCheckoutRouteImport } from './routes/api/public/billing/checkout'
import { Route as ApiPublicBillingPortalRouteImport } from './routes/api/public/billing/portal'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing/webhook'
import { Route as ApiPublicHooksRunTasksRouteImport } from './routes/api/public/hooks/run-tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute =
  Xmxhi72185Char3723ndgdjngfg17w7DothtmlRouteImport.update({
    id: '/xmxhi72185%23ndgdjngfg17w7.html',
    path: '/xmxhi72185%23ndgdjngfg17w7.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const EarlyAccessIndexRoute = EarlyAccessIndexRouteImport.update({
  id: '/early-access/',
  path: '/early-access/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessAdminRoute = EarlyAccessAdminRouteImport.update({
  id: '/early-access/admin',
  path: '/early-access/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessWelcomeRoute = EarlyAccessWelcomeRouteImport.update({
  id: '/early-access/welcome',
  path: '/early-access/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersDashboardRoute = PartnersDashboardRouteImport.update({
  id: '/partners/dashboard',
  path: '/partners/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipRoute = ApiPublicMembershipRouteImport.update({
  id: '/api/public/membership',
  path: '/api/public/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingCheckoutRoute =
  ApiPublicBillingCheckoutRouteImport.update({
    id: '/api/public/billing/checkout',
    path: '/api/public/billing/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingPortalRoute = ApiPublicBillingPortalRouteImport.update({
  id: '/api/public/billing/portal',
  path: '/api/public/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing/webhook',
  path: '/api/public/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunTasksRoute = ApiPublicHooksRunTasksRouteImport.update({
  id: '/api/public/hooks/run-tasks',
  path: '/api/public/hooks/run-tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/xmxhi72185%23ndgdjngfg17w7.html': typeof Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/early-access/admin': typeof EarlyAccessAdminRoute
  '/early-access/welcome': typeof EarlyAccessWelcomeRoute
  '/partners/dashboard': typeof PartnersDashboardRoute
  '/early-access/': typeof EarlyAccessIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/api/public/membership': typeof ApiPublicMembershipRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/hooks/run-tasks': typeof ApiPublicHooksRunTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/xmxhi72185%23ndgdjngfg17w7.html': typeof Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/early-access/admin': typeof EarlyAccessAdminRoute
  '/early-access/welcome': typeof EarlyAccessWelcomeRoute
  '/partners/dashboard': typeof PartnersDashboardRoute
  '/early-access': typeof EarlyAccessIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/api/public/membership': typeof ApiPublicMembershipRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/hooks/run-tasks': typeof ApiPublicHooksRunTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/xmxhi72185%23ndgdjngfg17w7.html': typeof Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/early-access/admin': typeof EarlyAccessAdminRoute
  '/early-access/welcome': typeof EarlyAccessWelcomeRoute
  '/partners/dashboard': typeof PartnersDashboardRoute
  '/early-access/': typeof EarlyAccessIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/api/public/membership': typeof ApiPublicMembershipRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/hooks/run-tasks': typeof ApiPublicHooksRunTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/checkout'
    | '/faq'
    | '/mcp'
    | '/settings'
    | '/sitemap.xml'
    | '/xmxhi72185%23ndgdjngfg17w7.html'
    | '/.well-known/oauth-protected-resource'
    | '/early-access/admin'
    | '/early-access/welcome'
    | '/partners/dashboard'
    | '/early-access/'
    | '/partners/'
    | '/api/public/membership'
    | '/api/public/billing/checkout'
    | '/api/public/billing/portal'
    | '/api/public/billing/webhook'
    | '/api/public/hooks/run-tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/checkout'
    | '/faq'
    | '/mcp'
    | '/settings'
    | '/sitemap.xml'
    | '/xmxhi72185%23ndgdjngfg17w7.html'
    | '/.well-known/oauth-protected-resource'
    | '/early-access/admin'
    | '/early-access/welcome'
    | '/partners/dashboard'
    | '/early-access'
    | '/partners'
    | '/api/public/membership'
    | '/api/public/billing/checkout'
    | '/api/public/billing/portal'
    | '/api/public/billing/webhook'
    | '/api/public/hooks/run-tasks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/checkout'
    | '/faq'
    | '/mcp'
    | '/settings'
    | '/sitemap.xml'
    | '/xmxhi72185%23ndgdjngfg17w7.html'
    | '/.well-known/oauth-protected-resource'
    | '/early-access/admin'
    | '/early-access/welcome'
    | '/partners/dashboard'
    | '/early-access/'
    | '/partners/'
    | '/api/public/membership'
    | '/api/public/billing/checkout'
    | '/api/public/billing/portal'
    | '/api/public/billing/webhook'
    | '/api/public/hooks/run-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqRoute: typeof FaqRoute
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute: typeof Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EarlyAccessAdminRoute: typeof EarlyAccessAdminRoute
  EarlyAccessWelcomeRoute: typeof EarlyAccessWelcomeRoute
  PartnersDashboardRoute: typeof PartnersDashboardRoute
  EarlyAccessIndexRoute: typeof EarlyAccessIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  ApiPublicMembershipRoute: typeof ApiPublicMembershipRoute
  ApiPublicBillingCheckoutRoute: typeof ApiPublicBillingCheckoutRoute
  ApiPublicBillingPortalRoute: typeof ApiPublicBillingPortalRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
  ApiPublicHooksRunTasksRoute: typeof ApiPublicHooksRunTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xmxhi72185%23ndgdjngfg17w7.html': {
      id: '/xmxhi72185%23ndgdjngfg17w7.html'
      path: '/xmxhi72185%23ndgdjngfg17w7.html'
      fullPath: '/xmxhi72185%23ndgdjngfg17w7.html'
      preLoaderRoute: typeof Xmxhi72185Char3723ndgdjngfg17w7DothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access/': {
      id: '/early-access/'
      path: '/early-access'
      fullPath: '/early-access/'
      preLoaderRoute: typeof EarlyAccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access/admin': {
      id: '/early-access/admin'
      path: '/early-access/admin'
      fullPath: '/early-access/admin'
      preLoaderRoute: typeof EarlyAccessAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access/welcome': {
      id: '/early-access/welcome'
      path: '/early-access/welcome'
      fullPath: '/early-access/welcome'
      preLoaderRoute: typeof EarlyAccessWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/dashboard': {
      id: '/partners/dashboard'
      path: '/partners/dashboard'
      fullPath: '/partners/dashboard'
      preLoaderRoute: typeof PartnersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership': {
      id: '/api/public/membership'
      path: '/api/public/membership'
      fullPath: '/api/public/membership'
      preLoaderRoute: typeof ApiPublicMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/checkout': {
      id: '/api/public/billing/checkout'
      path: '/api/public/billing/checkout'
      fullPath: '/api/public/billing/checkout'
      preLoaderRoute: typeof ApiPublicBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/portal': {
      id: '/api/public/billing/portal'
      path: '/api/public/billing/portal'
      fullPath: '/api/public/billing/portal'
      preLoaderRoute: typeof ApiPublicBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/webhook': {
      id: '/api/public/billing/webhook'
      path: '/api/public/billing/webhook'
      fullPath: '/api/public/billing/webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-tasks': {
      id: '/api/public/hooks/run-tasks'
      path: '/api/public/hooks/run-tasks'
      fullPath: '/api/public/hooks/run-tasks'
      preLoaderRoute: typeof ApiPublicHooksRunTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  FaqRoute: FaqRoute,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute:
    Xmxhi72185Char3723ndgdjngfg17w7DothtmlRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EarlyAccessAdminRoute: EarlyAccessAdminRoute,
  EarlyAccessWelcomeRoute: EarlyAccessWelcomeRoute,
  PartnersDashboardRoute: PartnersDashboardRoute,
  EarlyAccessIndexRoute: EarlyAccessIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  ApiPublicMembershipRoute: ApiPublicMembershipRoute,
  ApiPublicBillingCheckoutRoute: ApiPublicBillingCheckoutRoute,
  ApiPublicBillingPortalRoute: ApiPublicBillingPortalRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
  ApiPublicHooksRunTasksRoute: ApiPublicHooksRunTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
